//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetmarkBATDbConnector
{
    using System;
    using System.Collections.Generic;
    
    public partial class am_bat
    {
        public string UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Zip { get; set; }
        public string BrokerOrIRA { get; set; }
        public string DateStarted { get; set; }
        public Nullable<bool> EloquaUser { get; set; }
        public string TimeRange { get; set; }
        public string PracticeType { get; set; }
        public string AffiliationModel { get; set; }
        public string FirmType { get; set; }
        public string PDF { get; set; }
        public Nullable<bool> Page1Complete { get; set; }
        public Nullable<bool> Page2Complete { get; set; }
        public string Ff_TotalFirmAsset { get; set; }
        public string Ff_NonRecurringRevenue { get; set; }
        public string Ff_NonRecurringRevenue_Annualized { get; set; }
        public string Ff_RecurringRevenue { get; set; }
        public string Ff_RecurringRevenue_Annualized { get; set; }
        public string Ff_TotalRevenue { get; set; }
        public string Ff_TotalRevenue_Annualized { get; set; }
        public string Ff_DirectExpenses { get; set; }
        public string Ff_DirectExpenses_Annualized { get; set; }
        public string Ff_IndirectExpenses { get; set; }
        public string Ff_IndirectExpenses_Annualized { get; set; }
        public string Ff_OperatingProfit { get; set; }
        public string Ff_OperaintProfit_Annualized { get; set; }
        public string Ff_Projected_Growth { get; set; }
        public string Ff_Client_Relationships { get; set; }
        public string Ff_Fte_Non_Advisors { get; set; }
        public string Ff_Fte_Advisors { get; set; }
        public string Ff_New_Clients { get; set; }
        public string Vmi_Man_Written_Plan { get; set; }
        public string Vmi_Man_Track { get; set; }
        public string Vmi_Man_Phase { get; set; }
        public string Vmi_Man_Revenue { get; set; }
        public string Vmi_Man_Practice { get; set; }
        public string Vmi_Mar_Value_Proposition { get; set; }
        public string Vmi_Mar_Materials { get; set; }
        public string Vmi_Mar_Plan { get; set; }
        public string Vmi_Mar_Prospects { get; set; }
        public string Vmi_Mar_New_Business { get; set; }
        public string Vmi_Opt_Automate { get; set; }
        public string Vmi_Opt_Procedures { get; set; }
        public string Vmi_Opt_Segment { get; set; }
        public string Vmi_Opt_Model { get; set; }
        public string Vmi_Opt_Schedule { get; set; }
        public string Vmi_Emp_Human { get; set; }
        public string Vmi_Emp_Compensation { get; set; }
        public string Vmi_Emp_Responsibilities { get; set; }
        public string Vmi_Emp_Staff { get; set; }
        public string Vmi_Emp_Emp_Retention { get; set; }
        public string VmiIndex { get; set; }
    }
}
